version: "3.0"

expectations:
  population_size: 1000

actions:

# Match covid_all_for_matching to comparators in potential_historical_general_population and potential_contemporary_general_population
# https://docs.opensafely.org/case-control-studies/

# Extract data for covid_all_for_matching
  extract_covid_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_all_for_matching
    outputs:
      highly_sensitive:
        cohort: output/input_covid_all_for_matching.csv

  covid_all_descriptive:
    run: stata-mp:latest analysis/covid_all_for_matching.do
    needs: [extract_covid_all]
    outputs:
      highly_sensitive:
        analysis_dataset: output/input_covid_all_for_matching.csv
      moderately_sensitive:
        png1: output/krt_outcome_covid_severity.png 
        png2: output/krt_outcome_covid_acute_kidney_injury.png 
        png3: output/krt_outcome_covid_krt.png
        png4: output/krt_outcome_covid_vax_status.png
        png5: output/krt_outcome_calendar_period.png
        png6: output/mortality_covid_severity.png 
        png7: output/mortality_covid_acute_kidney_injury.png 
        png8: output/mortality_covid_krt.png
        png9: output/mortality_covid_vax_status.png
        png10: output/mortality_calendar_period.png
        png11: output/aki_covid_severity.png 
        png12: output/aki_covid_acute_kidney_injury.png 
        png13: output/aki_covid_krt.png
        png14: output/aki_covid_vax_status.png
        png15: output/aki_calendar_period.png