version: "3.0"

expectations:
  population_size: 1000

actions:

# Match covid_all_for_matching to comparators in potential_historical_general_population and potential_contemporary_general_population
# https://docs.opensafely.org/case-control-studies/

# Extract data for covid_all_for_matching
  extract_covid_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_all_for_matching
    outputs:
      highly_sensitive:
        cohort: output/input_covid_all_for_matching.csv

