
version: "3.0"

expectations:
  population_size: 1000

actions:

# Match covid_all_for_matching to comparators in potential_historical_general_population and potential_contemporary_general_population
# https://docs.opensafely.org/case-control-studies/

# Extract data for covid_all_for_matching
  extract_covid_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_all_for_matching
    outputs:
      highly_sensitive:
        cohort: output/input_covid_all_for_matching.csv

  covid_all_descriptive:
    run: stata-mp:latest analysis/covid_all_for_matching.do
    needs: [extract_covid_all]
    outputs:
      highly_sensitive:
        analysis_dataset: output/covid_all_for_matching.dta
      moderately_sensitive:
        log: logs/covid_all_for_matching.log

# Extract data for covid_critical_care
  extract_covid_critical_care:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_critical_care
    outputs:
      highly_sensitive:
        cohort: output/input_covid_critical_care.csv

  covid_critical_care_count:
    run: stata-mp:latest analysis/covid_critical_care.do
    needs: [extract_covid_critical_care]
    outputs:
      highly_sensitive:
        analysis_dataset: output/covid_critical_care.dta
      moderately_sensitive:
        log: logs/covid_critical_care.log

# Extract data for potential_contemporary_general_population
  extract_potential_contemporary_general_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_potential_contemporary_general_population
    outputs:
      highly_sensitive:
        cohort: output/input_potential_contemporary_general_population.csv
