
version: "3.0"

expectations:
  population_size: 1000

actions:

# Match covid_all_for_matching to comparators in potential_historical_general_population and potential_contemporary_general_population
# https://docs.opensafely.org/case-control-studies/

# Extract data for covid_england
  extract_covid_england:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_england
    outputs:
      highly_sensitive:
        cohort: output/input_covid_england.csv

#Data management for covid_england
  covid_england:
    run: stata-mp:latest analysis/covid_england.do
    needs: [extract_covid_england]
    outputs:
      highly_sensitive:
        analysis_dataset: output/covid_england.dta
      moderately_sensitive:
        log: logs/covid_england.log

#Descriptive statitics for covid_england
  covid_descriptive:
    run: stata-mp:latest analysis/covid_descriptive.do
    needs: [covid_england]
    outputs:
      highly_sensitive:
        analysis_dataset: output/covid_descriptive.dta
      moderately_sensitive:
        log: logs/covid_descriptive.log

#Extract matching and exclusion data for potential_contemporary_population_england
  extract_potential_contemporary_population_england:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_potential_contemporary_population_england
    outputs:
      highly_sensitive:
        cohort: output/input_potential_contemporary_population_england.csv

# Extract data for covid_northeast
  extract_covid_northeast:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_northeast
    outputs:
      highly_sensitive:
        cohort: output/input_covid_northeast.csv

#Data management for covid_northeast
  covid_northeast:
    run: stata-mp:latest analysis/covid_northeast.do
    needs: [extract_covid_northeast]
    outputs:
      highly_sensitive:
        analysis_dataset: output/covid_northeast.dta
      moderately_sensitive:
        log: logs/covid_northeast.log

#Extract matching and exclusion data for potential_contemporary_population_northeast
  extract_potential_contemporary_population_northeast:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_potential_contemporary_population_northeast
    outputs:
      highly_sensitive:
        cohort: output/input_potential_contemporary_population_northeast.csv

#Data management for potential_contemporary_population_northeast
  potential_contemporary_population_northeast:
    run: stata-mp:latest analysis/potential_contemporary_population_northeast.do
    needs: [extract_potential_contemporary_population_northeast]
    outputs:
      highly_sensitive:
        analysis_dataset: output/potential_contemporary_population_northeast.dta
      moderately_sensitive:
        log: logs/potential_contemporary_population_northeast.log

# Match covid_northeast to potential_contemporary_population_northeast
  matching:
    run: python:latest python analysis/match_contemporary_northeast.py
    needs: [extract_covid_northeast, covid_northeast, extract_potential_contemporary_population_northeast, potential_contemporary_population_northeast]
    outputs:
      moderately_sensitive:
        matching_report: output/matching_report_contemporary_northeast.txt
      highly_sensitive:
        matched_matches: output/matched_matches_contemporary_northeast.csv


# Extract data for covid_critical_care
  extract_covid_critical_care:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_covid_critical_care
    outputs:
      highly_sensitive:
        cohort: output/input_covid_critical_care.csv

  covid_critical_care_count:
    run: stata-mp:latest analysis/covid_critical_care.do
    needs: [extract_covid_critical_care]
    outputs:
      highly_sensitive:
        analysis_dataset: output/covid_critical_care.dta
      moderately_sensitive:
        log: logs/covid_critical_care.log

# Extract data for potential_contemporary_general_population
  extract_potential_contemporary_general_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_potential_contemporary_general_population
    outputs:
      highly_sensitive:
        cohort: output/input_potential_contemporary_general_population.csv

# Extract data for potential_contemporary_general_population (North East region)
  extract_potential_contemporary_general_population_northeast:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_potential_contemporary_general_population_northeast
    outputs:
      highly_sensitive:
        cohort: output/input_potential_contemporary_general_population_northeast.csv
